export const CONFIG = {
  AUTH0_DOMAIN: process.env.EXPO_PUBLIC_AUTH0_DOMAIN ?? '',
  AUTH0_CLIENT_ID: process.env.EXPO_PUBLIC_AUTH0_CLIENT_ID ?? '',
  AUTH0_AUDIENCE: process.env.EXPO_PUBLIC_AUTH0_AUDIENCE ?? '',
};
